import Foundation

runGearTests()
runGearConfigTests()
runGearConfigStoreTests()
runShiftCommandsTests()
runSessionRegistryTests()
runRegisterScriptFixtureTests()
runSessionTitleTests()
runSessionInfoTests()
runWarpTitleTests()
runTabSearchTests()
runTranscriptStateTests()
runCommandConfirmationTests()
runShiftSafetyTests()
runTerminalKindTests()
runTerminalScriptsTests()
runProjectNamingTests()
runShifterGeometryTests()
runTokenParsingTests()
runTokenMeterTests()
runSoundSynthTests()

runTurboPasswordsTests()
print("\n\(passes) passed, \(failures) failed")
exit(failures == 0 ? 0 : 1)
